rss_feeds:
  - url: "https://huggingface.co/blog/feed.xml" 
    weight: 1.0

target_duration: 1  # minutes
dedupe_threshold: 0.9

voice_settings:
  provider: "dummy"  # use dummy TTS for testing
  speed: 1.0
  voice_id: "default"

output:
  audio_format: "wav"
  sample_rate: 44100
  episode_filename: "episode.wav"
  rss_filename: "feed.xml"