rss_feeds:
  - url: "https://blog.openai.com/rss.xml"
    weight: 1.0
  - url: "https://huggingface.co/blog/feed.xml" 
    weight: 1.0
  - url: "https://www.anthropic.com/news/rss.xml"
    weight: 1.0

target_duration: 10  # minutes
dedupe_threshold: 0.9

voice_settings:
  provider: "espeak"  # fallback for step 1
  speed: 1.0
  voice_id: "default"

output:
  audio_format: "wav"
  sample_rate: 44100
  episode_filename: "episode.wav"
  rss_filename: "feed.xml"