# Step 3: Production Audio Pipeline Configuration
rss_feeds:
  - url: "https://www.technologyreview.com/feed/"
    weight: 1.0
  - url: "https://bullrich.dev/tldr-rss/ai.rss"
    weight: 1.0

target_duration: 10  # minutes
dedupe_threshold: 0.9

# Voice settings with MiniMax support
voice_settings:
  provider: "minimax"  # "minimax", "espeak", "dummy"
  wpm: 165  # words per minute (comfortable listening speed)
  voice_id: "English_captivating_female1"  # MiniMax voice ID
  # MiniMax-specific settings
  speed: 1.0    # 0.5-2.0 speed multiplier
  vol: 1.0      # Volume level
  pitch: 0.0    # Pitch adjustment

# Professional audio processing
audio:
  use_professional_stitcher: true  # Use ProfessionalAudioStitcher with pydub
  gap_ms: 500                      # Gap between segments (ms)
  fade_ms: 50                      # Fade in/out duration (ms)
  target_lufs: -19.0               # Target loudness (broadcast standard)
  normalize_audio: true            # Apply audio normalization

# Output configuration
output:
  audio_format: "mp3"          # "wav" or "mp3"
  sample_rate: 44100
  bitrate: "128k"              # MP3 bitrate
  episode_filename: "episode.mp3"
  rss_filename: "feed.xml"
  script_filename: "episode_script.txt"

# Processing configuration (from Step 2)
processing:
  summarizer: "openai"
  max_words: 50
  openai_model: "gpt-4o-mini"
  openai_temperature: 0.3
  
  deduplicator: "semantic"
  similarity_threshold: 0.85
  embedding_model: "all-MiniLM-L6-v2"
  embedding_cache_days: 7
  
  use_readability: true
  fetch_full_content: true
  content_timeout: 10
  max_quote_words: 30

  # Policy checks configuration - split into pre-LLM and post-LLM phases
  policy_checks:
    # Pre-LLM checks (applied before OpenAI call - fast and cheap)
    paywall_detection: false
    min_content_length: true
    content_quality_check: true
    url_allowlist_check: false
    
    # Post-LLM checks (applied after OpenAI call)
    max_word_count: false
    quote_length_check: true
    derivative_language_check: false
    transformative_analysis_check: false  # Set to false for testing if too strict